--INSERT INTO APP.SYNCDBPROPS(ID, DBNAME, POSNAME, STOCKNAME) VALUES (1, 'Bistro-1', 'POSBistro1', 'Bistro1 stock');


--insert into APP.SYNCDATAOUT (ID, DBID, SENDERTABLENAME,SENDERTABLEIDNAME,SENDERTABLEIDVAL , SENDDATE, RECIPIENTTABLENAME,RECIPIENTTABLEIDNAME,RECIPIENTTABLEIDVAL, RECIEPTDATE, STATUS, ATTEMPTSCOUNT, MSG)
/*insert into APP.SYNCDATAOUT (DBID, SENDERTABLENAME, SENDERTABLEIDNAME,SENDERTABLEIDVAL, CRDATE, ATTEMPTSCOUNT)
select 1, 'APP.TICKETS','ID',t.ID, CURRENT_TIMESTAMP, 0
    from APP.TICKETS t
    inner join APP.RECEIPTS r on r.ID=t.ID
    where t.TICKETID>60000 ;*/

--select * from SYNCDBPROPS;
--delete from APP.SYNCDATAOUT;
select * from APP.SYNCDATAOUT;
--select CURRENT_TIMESTAMP from APP.SYNCDBPROPS;