-------------------------update for v.1.5.1-------------------------

CREATE TRIGGER APP.CLOSEDCASH_SYNC_REG_INS
AFTER INSERT ON APP.CLOSEDCASH
REFERENCING NEW_TABLE AS NEW_TABLE
FOR EACH STATEMENT
  insert into APP.SYNCDATAOUT (OTYPE, TABLENAME, TABLEKEY1IDNAME, TABLEKEY1IDVAL, CRDATE, ATTEMPTSCOUNT)
    select 'I','APP.CLOSEDCASH','MONEY',MONEY,CURRENT_TIMESTAMP,0  from NEW_TABLE where SESSION_USER<>'APPSYNCSRV';

CREATE TRIGGER APP.CLOSEDCASH_SYNC_REG_UPD
AFTER UPDATE ON APP.CLOSEDCASH
REFERENCING NEW_TABLE AS NEW_TABLE
FOR EACH STATEMENT
  insert into APP.SYNCDATAOUT (OTYPE, TABLENAME, TABLEKEY1IDNAME, TABLEKEY1IDVAL, CRDATE, ATTEMPTSCOUNT)
    select 'U','APP.CLOSEDCASH','MONEY',MONEY,CURRENT_TIMESTAMP,0  from NEW_TABLE where SESSION_USER<>'APPSYNCSRV';

CREATE TRIGGER APP.CLOSEDCASH_SYNC_REG_DEL
AFTER DELETE ON APP.CLOSEDCASH
REFERENCING OLD_TABLE AS OLD_TABLE
FOR EACH STATEMENT
  insert into APP.SYNCDATAOUT (OTYPE, TABLENAME, TABLEKEY1IDNAME, TABLEKEY1IDVAL, CRDATE, ATTEMPTSCOUNT)
    select 'D','APP.CLOSEDCASH','MONEY',MONEY,CURRENT_TIMESTAMP,0  from OLD_TABLE where SESSION_USER<>'APPSYNCSRV';


CREATE TRIGGER APP.RECEIPTS_PURPOSES_SYNC_REG_INS
AFTER INSERT ON APP.RECEIPTS_PURPOSES
REFERENCING NEW_TABLE AS NEW_TABLE
FOR EACH STATEMENT
  insert into APP.SYNCDATAOUT (OTYPE, TABLENAME, TABLEKEY1IDNAME, TABLEKEY1IDVAL, CRDATE, ATTEMPTSCOUNT)
    select 'I','APP.RECEIPTS_PURPOSES','RECEIPT_ID',RECEIPT_ID,CURRENT_TIMESTAMP,0  from NEW_TABLE where SESSION_USER<>'APPSYNCSRV';

CREATE TRIGGER APP.RECEIPTS_PURPOSES_SYNC_REG_UPD
AFTER UPDATE ON APP.RECEIPTS_PURPOSES
REFERENCING NEW_TABLE AS NEW_TABLE
FOR EACH STATEMENT
  insert into APP.SYNCDATAOUT (OTYPE, TABLENAME, TABLEKEY1IDNAME, TABLEKEY1IDVAL, CRDATE, ATTEMPTSCOUNT)
    select 'U','APP.RECEIPTS_PURPOSES','RECEIPT_ID',RECEIPT_ID,CURRENT_TIMESTAMP,0  from NEW_TABLE where SESSION_USER<>'APPSYNCSRV';

CREATE TRIGGER APP.RECEIPTS_PURPOSES_SYNC_REG_DEL
AFTER DELETE ON APP.RECEIPTS_PURPOSES
REFERENCING OLD_TABLE AS OLD_TABLE
FOR EACH STATEMENT
  insert into APP.SYNCDATAOUT (OTYPE, TABLENAME, TABLEKEY1IDNAME, TABLEKEY1IDVAL, CRDATE, ATTEMPTSCOUNT)
    select 'D','APP.RECEIPTS_PURPOSES','RECEIPT_ID',RECEIPT_ID,CURRENT_TIMESTAMP,0  from OLD_TABLE where SESSION_USER<>'APPSYNCSRV';


CREATE TRIGGER APP.RECEIPT_PURPOSES_SYNC_REG_INS
AFTER INSERT ON APP.RECEIPT_PURPOSES
REFERENCING NEW_TABLE AS NEW_TABLE
FOR EACH STATEMENT
  insert into APP.SYNCDATAOUT (OTYPE, TABLENAME, TABLEKEY1IDNAME, TABLEKEY1IDVAL, CRDATE, ATTEMPTSCOUNT)
    select 'I','APP.RECEIPT_PURPOSES','ID',ID,CURRENT_TIMESTAMP,0  from NEW_TABLE where SESSION_USER<>'APPSYNCSRV';

CREATE TRIGGER APP.RECEIPT_PURPOSES_SYNC_REG_UPD
AFTER UPDATE ON APP.RECEIPT_PURPOSES
REFERENCING NEW_TABLE AS NEW_TABLE
FOR EACH STATEMENT
  insert into APP.SYNCDATAOUT (OTYPE, TABLENAME, TABLEKEY1IDNAME, TABLEKEY1IDVAL, CRDATE, ATTEMPTSCOUNT)
    select 'U','APP.RECEIPT_PURPOSES','ID',ID,CURRENT_TIMESTAMP,0  from NEW_TABLE where SESSION_USER<>'APPSYNCSRV';

CREATE TRIGGER APP.RECEIPT_PURPOSES_SYNC_REG_DEL
AFTER DELETE ON APP.RECEIPT_PURPOSES
REFERENCING OLD_TABLE AS OLD_TABLE
FOR EACH STATEMENT
  insert into APP.SYNCDATAOUT (OTYPE, TABLENAME, TABLEKEY1IDNAME, TABLEKEY1IDVAL, CRDATE, ATTEMPTSCOUNT)
    select 'D','APP.RECEIPT_PURPOSES','ID',ID,CURRENT_TIMESTAMP,0  from OLD_TABLE where SESSION_USER<>'APPSYNCSRV';
